version: "3.8"
services:
  postgres:
    image: postgres:13.3
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: agg_app_db
    volumes:
      - "./volumes/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql"